# Copyright 2021 JD.com, Inc., JD AI
"""
@author: Yehao Li
@contact: yehaoli.sysu@gmail.com
"""

from .config import CfgNode as CN

_K = CN()

kfg = _K

_K.IDS = 'IDS'

_K.COCO_IDS = 'COCO_IDS'

_K.CROWD_IDS = 'CROWD_IDS'

_K.COCO_IMG_INPUT = 'COCO_IMG_INPUT'

_K.CROWD_IMG_INPUT = 'CROWD_IMG_INPUT'

_K.COCO_SENT_FEATS = 'COCO_SENT_FEATS'

_K.CROWD_SENT_FEATS = 'CROWD_SENT_FEATS'

_K.COCO_MERGE_FEATS = 'COCO_MERGE_FEATS'

_K.CROWD_MERGE_FEATS = 'CROWD_MERGE_FEATS'

_K.COCO_GLOBAL_FEATS = 'COCO_GLOBAL_FEATS'

_K.CROWD_GLOBAL_FEATS = 'CROWD_GLOBAL_FEATS'

_K.COCO_D_G_LOGITS = 'COCO_D_G_LOGITS'

_K.COCO_E_G_LOGITS = 'COCO_E_G_LOGITS'

_K.CROWD_D_G_LOGITS = 'CROWD_D_G_LOGITS'

_K.CROWD_E_G_LOGITS = 'CROWD_E_G_LOGITS'

_K.COCO_E_G_HIDDEN_STATES = 'COCO_E_G_HIDDEN_STATES'

_K.COCO_D_G_HIDDEN_STATES = 'COCO_D_G_HIDDEN_STATES'

_K.CROWD_E_G_HIDDEN_STATES = 'CROWD_E_G_HIDDEN_STATES'

_K.CROWD_D_G_HIDDEN_STATES = 'CROWD_D_G_HIDDEN_STATES'

_K.CROWD_TOKENS_MASKS = 'CROWD_TOKENS_MASKS'

_K.COCO_TOKENS_MASKS = 'COCO_TOKENS_MASKS'

_K.COCO_ATT_MASKS = 'COCO_ATT_MASKS'

_K.CROWD_ATT_MASKS = 'CROWD_ATT_MASKS'

_K.CROWD_EXT_ATT_MASKS = 'CROWD_EXT_ATT_MASKS'

_K.COCO_EXT_ATT_MASKS = 'COCO_EXT_ATT_MASKS'

_K.CROWD_EXT_U_TOKENS_MASKS = 'CROWD_EXT_U_TOKENS_MASKS'

_K.COCO_EXT_U_TOKENS_MASKS = 'COCO_EXT_U_TOKENS_MASKS'

_K.CROWD_EXT_G_TOKENS_MASKS = 'CROWD_EXT_G_TOKENS_MASKS'

_K.COCO_EXT_G_TOKENS_MASKS = 'COCO_EXT_G_TOKENS_MASKS'

_K.COCO_E_G_TOKEN_EMBED = 'COCO_E_G_TOKEN_EMBED'

_K.COCO_D_G_TOKEN_EMBED = 'COCO_D_G_TOKEN_EMBED'

_K.CROWD_E_G_TOKEN_EMBED = 'CROWD_E_G_TOKEN_EMBED'

_K.CROWD_D_G_TOKEN_EMBED = 'CROWD_D_G_TOKEN_EMBED'
###############################
_K.COCO_E_P_ATT_FEATS = 'COCO_E_P_ATT_FEATS'
_K.CROWD_E_P_ATT_FEATS = 'CROWD_E_P_ATT_FEATS'
_K.COCO_D_P_ATT_FEATS = 'COCO_D_P_ATT_FEATS'
_K.CROWD_D_P_ATT_FEATS = 'CROWD_D_P_ATT_FEATS'
###############################
_K.COCO_E_G_HIDDEN_STATES = 'COCO_E_G_HIDDEN_STATES'
_K.COCO_D_G_HIDDEN_STATES = 'COCO_D_G_HIDDEN_STATES'
_K.CROWD_E_G_HIDDEN_STATES = 'CROWD_E_G_HIDDEN_STATES'
_K.CROWD_D_G_HIDDEN_STATES = 'CROWD_D_G_HIDDEN_STATES'
###############################
_K.COCO_E_G_CELL_STATES = 'COCO_E_G_CELL_STATES'
_K.COCO_D_G_CELL_STATES = 'COCO_D_G_CELL_STATES'
_K.CROWD_E_G_CELL_STATES = 'CROWD_E_G_CELL_STATES'
_K.CROWD_D_G_CELL_STATES = 'CROWD_D_G_CELL_STATES'
###############################
_K.COCO_OUT_IDS = 'COCO_OUT_IDS'
_K.CROWD_OUT_IDS = 'CROWD_OUT_IDS'
_K.COCO_REOUT_IDS = 'COCO_REOUT_IDS'
_K.CROWD_REOUT_IDS = 'CROWD_REOUT_IDS'
########################################## TOKENS ##########################################
_K.U_TOKENS_IDS = 'U_TOKENS_IDS'

_K.U_TOKENS_IDS_WO_MASK = 'U_TOKENS_IDS_WO_MASK'

_K.G_TOKENS_IDS = 'G_TOKENS_IDS'

_K.COCO_G_TOKENS_IDS = 'COCO_G_TOKENS_IDS'

_K.CROWD_G_TOKENS_IDS = 'CROWD_G_TOKENS_IDS'

_K.RELATION = 'RELATION'

_K.ATTRIBUTE = 'ATTRIBUTE'

_K.U_TOKENS_TYPE = 'U_TOKENS_TYPE'

_K.G_TOKENS_TYPE = 'G_TOKENS_TYPE'

_K.COCO_G_TOKENS_TYPE = 'COCO_G_TOKENS_TYPE'

_K.CROWD_G_TOKENS_TYPE = 'CROWD_G_TOKENS_TYPE'

_K.U_TOKEN_EMBED = 'U_TOKEN_EMBED'

_K.G_TOKEN_EMBED = 'G_TOKEN_EMBED'

########################################## MASKS ##########################################
_K.TOKENS_MASKS = 'TOKENS_MASKS'

_K.EXT_U_TOKENS_MASKS = 'EXT_U_TOKENS_MASKS'

_K.EXT_G_TOKENS_MASKS = 'EXT_G_TOKENS_MASKS'

########################################## TARGET ##########################################
_K.U_TARGET_IDS = 'U_TARGET_IDS'

_K.G_TARGET_IDS = 'G_TARGET_IDS'

_K.COCO_G_TARGET_IDS = 'COCO_G_TARGET_IDS'

_K.CROWD_G_TARGET_IDS = 'CROWD_G_TARGET_IDS'

_K.V_TARGET = 'V_TARGET'

_K.V_TARGET_LABELS = 'V_TARGET_LABELS'

_K.ITM_NEG_LABEL = 'ITM_NEG_LABEL'

########################################## FEATS ##########################################
_K.COCO_ATT_FEATS = 'COCO_ATT_FEATS'

_K.CROWD_ATT_FEATS = 'CROWD_ATT_FEATS'

_K.ATT_FEATS = 'ATT_FEATS'

_K.ATT_FEATS_WO_MASK = 'ATT_FEATS_WO_MASK'

_K.ATT_MASKS = 'ATT_MASKS'

_K.EXT_ATT_MASKS = 'EXT_ATT_MASKS'

_K.ATT_FEATS_LOC = 'ATT_FEATS_LOC'

_K.P_ATT_FEATS = 'P_ATT_FEATS'

_K.GLOBAL_FEATS = 'GLOBAL_FEATS'

########################################## STATES ##########################################
_K.U_HIDDEN_STATES = 'U_HIDDEN_STATES'

_K.G_HIDDEN_STATES = 'G_HIDDEN_STATES'

_K.HISTORY_STATES = 'HISTORY_STATES'

_K.ENC_HISTORY_STATES = 'ENC_HISTORY_STATES'

_K.U_CELL_STATES = 'U_CELL_STATES'

_K.G_CELL_STATES = 'G_CELL_STATES'

########################################## LOGITS ##########################################
_K.U_LOGITS = 'U_LOGITS'

_K.G_LOGITS = 'G_LOGITS'

_K.V_LOGITS = 'V_LOGITS'

_K.V_REGRESS = 'V_REGRESS'

_K.ITM_LOGITS = 'ITM_LOGITS'

########################################## Others ##########################################
_K.SEQ_PER_SAMPLE = 'SEQ_PER_SAMPLE'

_K.STYLE = 'STYLE'

_K.STYLE_ID = 'STYLE_ID'

_K.SAMPLE_PER_SAMPLE = 'SAMPLE_PER_SAMPLE'

_K.SEQ_PER_SAMPLE_NET1 = 'SEQ_PER_SAMPLE_NET1'

_K.SEQ_PER_SAMPLE_NET2 = 'SEQ_PER_SAMPLE_NET2'

_K.G_SENTS_IDS = 'G_SENTS_IDS'

_K.G_LOGP = 'G_LOGP'

_K.OUTPUT = 'OUTPUT'

_K.REOUTPUT = 'REOUTPUT'

_K.DECODE_BY_SAMPLE = 'DECODE_BY_SAMPLE'

_K.REWARDS = 'REWARDS'

_K.SS_PROB = 'SS_PROB'

_K.TIME_STEP = 'TIME_STEP'

_K.COCO_PATH = '../coco_caption'

_K.TEMP_DIR = './data/temp'

########################################## COSNet ##########################################
_K.SEMANTICS_IDS = 'SEMANTICS_IDS'

_K.SEMANTICS_MASK = 'SEMANTICS_MASK'

_K.EXT_SEMANTICS_MASKS = 'EXT_SEMANTICS_MASKS'

_K.SEMANTICS_LABELS = 'SEMANTICS_LABELS'

_K.SEMANTICS_MISS_LABELS = 'SEMANTICS_MISS_LABELS'

_K.SEMANTICS_PRED = 'SEMANTICS_PRED'

_K.SEMANTICS_FEATS = 'SEMANTICS_FEATS'

_K.SEMANTICS_POS_PRED = 'SEMANTICS_POS_PRED'